# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true

[character]
error_symbol = "[✗](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
disabled = true

[git_branch]
truncation_length = 20

[git_status]
ahead = "[⇡${count}](blue)"
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](blue)"
behind = "[⇣${count}](blue)"
up_to_date = "[✓](green)"
untracked = "[?](red)"
modified = "[+${count}](red)"
staged = "[+${count}](yellow)"
renamed = "[»${count}](red)"
deleted = "[-${count}](red)"
style = "green"

# https://starship.rs/ja-JP/presets/no-runtimes.html
[buf]
format = "[$symbol]($style)"

[cmake]
format = "[$symbol]($style)"

[cobol]
format = "[$symbol]($style)"

[crystal]
format = "[$symbol]($style)"

[daml]
format = "[$symbol]($style)"

[dart]
format = "[$symbol]($style)"

[deno]
format = "[$symbol]($style)"

[dotnet]
format = "[$symbol(🎯 $tfm )]($style)"

[elixir]
format = '[$symbol]($style)'

[elm]
format = '[$symbol]($style)'

[erlang]
format = '[$symbol]($style)'

[golang]
format = '[$symbol]($style)'

[helm]
format = '[$symbol]($style)'

[julia]
format = '[$symbol]($style)'

[kotlin]
format = '[$symbol]($style)'

[lua]
format = '[$symbol]($style)'

[nim]
format = '[$symbol]($style)'

[nodejs]
format = '[$symbol]($style)'

[ocaml]
format = '[$symbol(\($switch_indicator$switch_name\) )]($style)'

[perl]
format = '[$symbol]($style)'

[php]
format = '[$symbol]($style)'

[pulumi]
format = '[$symbol$stack]($style)'

[purescript]
format = '[$symbol]($style)'

[python]
format = '[$symbol]($style)'

[raku]
format = '[$symbol]($style)'

[red]
format = '[$symbol]($style)'

[rlang]
format = '[$symbol]($style)'

[ruby]
format = '[$symbol]($style)'

[rust]
format = '[$symbol]($style)'

[swift]
format = '[$symbol]($style)'

[vagrant]
format = '[$symbol]($style)'

[vlang]
format = '[$symbol]($style)'

[zig]
format = '[$symbol]($style)'
